app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    
    # Configuraciones de la aplicación
    app.config.from_object('config.Config')
    
    with app.app_context():
        # Importar Blueprints
        from .routes import user_routes
        # Registrar Blueprints
        app.register_blueprint(user_routes.bp)
        
    return app

app/routes/user_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from ..utils.data_processing import process_regression_data, train_regression_model, load_dataset

bp = Blueprint('main', __name__)

@bp.route('/', methods=['GET'])
def home():
    return render_template('home.html')

@bp.route('/regression', methods=['GET', 'POST'])
def regression(): 
    if request.method == 'POST':
        try:
            dataset_file = request.files.get('dataset')
            url = request.form.get('url')

            if not dataset_file and not url:
                return jsonify({'status': 'error', 'message': 'No dataset file or URL provided.'})

            dataset = load_dataset(file=dataset_file, url=url)

            input_variables_text = request.form.get('input_variables_text')
            output_variable_text = request.form.get('output_variable_text')

            if not input_variables_text or not output_variable_text:
                return jsonify({'status': 'error', 'message': 'Input and output variables are required.'})

            input_cols = [col.strip() for col in input_variables_text.split(',')]
            output_col = output_variable_text.strip()

            X, y = process_regression_data(dataset, input_cols, output_col)

            model_type = request.form.get('model')
            params = {}
            if model_type == 'polynomial':
                params['degree'] = int(request.form.get('degree', 2))
            elif model_type in ['ridge', 'lasso']:
                params['alpha'] = float(request.form.get('alpha', 1.0))
            elif model_type == 'neural_network':
                params['neurons'] = int(request.form.get('neurons', 10))
                params['hidden_activation'] = request.form.get('hidden_activation', 'relu')
                params['output_activation'] = request.form.get('output_activation', 'linear')
                params['layers'] = int(request.form.get('layers', 1))
                params['epochs'] = int(request.form.get('epochs', 100))

            model, history, plot_div, redirect_url = train_regression_model(X, y, model_type, **params)

            return jsonify({'status': 'success', 'plot_div': plot_div, 'redirect': redirect_url}), 200

        except Exception as e:
            print(f"Error occurred: {e}")
            return jsonify({'status': 'error', 'message': str(e)}), 500
    
    return render_template('regression.html')

@bp.route('/classification', methods=['GET', 'POST'])
def classification():
    if request.method == 'POST':
        dataset = request.files.get('dataset')
        url = request.form.get('url')
        neurons = request.form.get('neurons')
        model = request.form.get('model')
        hidden_activation = request.form.get('hidden_activation')
        output_activation = request.form.get('output_activation')
        layers = request.form.get('layers')
        epoch = request.form.get('epoch')

        return redirect(url_for('main.home'))

    return render_template('classification.html')

@bp.route('/results', methods=['GET'])
def results():
    plot_div = request.args.get('plot_div')
    return render_template('results.html', plot_div=plot_div)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}NeuronalHub{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='icons/bot_icon.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="https://kit.fontawesome.com/ee0f2a0585.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <a href="#" class="logo">NHub</a>
        <ul>
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.regression') }}">Regression</a></li>
            <li><a href="{{ url_for('main.classification') }}">Classification</a></li>
        </ul>
    </header>

    <section class="banner">
        <h1 class="banner-title" id="banner-text"></h1>
        <div class="cursor" id="cursor"></div>
        <div class="area">
            <ul class="circles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
            <div class="air air1"></div>
            <div class="air air2"></div>
            <div class="air air3"></div>
            <div class="air air4"></div>
        </div>
    </section>

    <script type="text/javascript">
        window.addEventListener("scroll", function() {
            var header = document.querySelector("header");
            header.classList.toggle("sticky", window.scrollY > 0);
        });

        document.addEventListener("DOMContentLoaded", function() {
            var footer = document.querySelector("footer");
            if (window.scrollY === 0) {
                footer.style.transition = "transform 0.6s";
                footer.style.transform = "translateY(100%)";
            }

            window.addEventListener("scroll", function() {
                if (window.scrollY === 0) {
                    footer.style.transition = "transform 0.6s";
                    footer.style.transform = "translateY(100%)";
                } else {
                    footer.style.transition = "transform 0.6s";
                    footer.style.transform = "translateY(0)";
                }
            });
        });
        
        const text = "Welcome To NeuronalHub";
        const speed = 100; // Velocidad de escritura

        let i = 0;
        function typeWriter() {
            if (i < text.length) {
                document.getElementById("banner-text").innerHTML += text.charAt(i);
                i++;
                setTimeout(typeWriter, speed);
            } else {
                document.getElementById("cursor").style.opacity = "1"; // Mostrar el cursor
            }
        }

        // Llama a la función typeWriter después de que el contenido se haya cargado
        document.addEventListener("DOMContentLoaded", function() {
            typeWriter();
        });

    </script>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <div class="footer-content">
            <div class="footer-text">
                <p>&copy; 2024 AI PROGRAMMERS</p>
            </div>
            <div class="footer-icons">
                <a href="#"><i class="fa-solid fa-envelope"></i></a>
                <a href="#"><i class="fa-brands fa-github"></i></a>
                <a href="#"><i class="fa-solid fa-newspaper"></i></a>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/classification.html
{% extends 'base.html' %}

{% block title %}Classification{% endblock %}

{% block content %}
<div class="introContainer2">
    <h2 class="introTitle2">Classification</h2>
</div>
<div class="form-image-container">
    <form action="{{ url_for('main.classification') }}" method="POST" enctype="multipart/form-data" class="form">
        <div class="form-group">
            <button type="button" class="btn">
                <input type="file" id="dataset" name="dataset" accept=".csv, .xlsx, .xls, .json" class="file-input" onchange="updateFileName(this)" />
                <i class="fa-solid fa-file-arrow-up" style="font-size: 15px; margin-right: 5px;"></i>Upload File
            </button>
            <label for="dataset">Upload Dataset (CSV)</label>
            <span id="fileStatusIcon"><i class="fa-solid fa-circle-xmark" style="color: red; margin-left: 8px;"></i></span>
        </div>
        <div class="form-group">
            <input type="url" id="url" name="url" placeholder=" " />
            <label for="url">Or Enter Dataset URL</label>
        </div>
        <div class="form-group">
            <input type="number" id="neurons" name="neurons" min="1" max="1000" placeholder=" " />
            <label for="neurons">Number of Neurons</label>
        </div>
        <div class="form-group">
            <select id="model" name="model" required>
                <option value="logistic">Logistic Regression</option>
                <option value="decision_tree">Decision Tree</option>
                <option value="random_forest">Random Forest</option>
                <option value="svm">Support Vector Machine</option>
            </select>
            <label for="model" style="color: #ccc; font-size: 16px; margin: 3px;">Select Model Type</label>
        </div>
        <div class="form-group">
            <select id="hidden_activation" name="hidden_activation" required>
                <option value="relu">ReLU</option>
                <option value="sigmoid">Sigmoid</option>
                <option value="tanh">Tanh</option>
                <option value="linear">Linear</option>
            </select>
            <label for="hidden_activation" style="color: #ccc; font-size: 16px; margin: 3px;">Select Hidden Activation Function</label>
        </div>
        <div class="form-group">
            <select id="output_activation" name="output_activation" required>
                <option value="softmax">Softmax</option>
                <option value="sigmoid">Sigmoid</option>
                <option value="tanh">Tanh</option>
                <option value="linear">Linear</option>
            </select>
            <label for="output_activation" style="color: #ccc; font-size: 16px; margin: 3px;">Select Output Activation Function</label>
        </div>
        <div class="form-group">
            <input type="number" id="layers" name="layers" min="1" max="10" placeholder=" " />
            <label for="layers">Number of Hidden Layers</label>
        </div>
        <div class="form-group">
            <input type="number" id="epoch" name="epoch" min="1" max="" placeholder=" " />
            <label for="epoch">Number of Epochs</label>
        </div>
        <div id="container">
            <div class="wrapper">
                <button class="button" type="submit">Submit</button>
            </div>
        </div>    
    </form>
    <div class="image">
        <img src="static/AI2.png" alt="Imagen descriptiva o animación">
    </div>
</div>

<script>
    const fileInput = document.getElementById('dataset');
    const fileStatusIcon = document.getElementById('fileStatusIcon');

    fileInput.addEventListener('change', function() {
        if (fileInput.files.length > 0) {
            fileStatusIcon.innerHTML = '<i class="fa-solid fa-circle-check" style="color: #00F10B; margin-left: 8px;"></i>';
        } else {
            fileStatusIcon.innerHTML = '<i class="fa-solid fa-circle-xmark" style="color: red;"></i>';
        }
    });
</script>
{% endblock %}

app/templates/home.html
<!-- home.html -->
{% extends 'base.html' %}

{% block title %}NeuronalHub{% endblock %}

{% block content %}
<div class="introContainer">
    <h2 class="introTitle">Neural Networks and Deep Learning</h2>
    <h3 class="contTitle">Discover how neural networks and deep learning are transforming the digital world, from machine translation to image recognition. Explore concepts, applications and advances on this page designed for beginners and experts alike.</h3>
</div>

<div class="cardsContainer">
    <div class="card">
        <div class="content">
            <div class="front">
                <p>What are Neural Networks?</p>
            </div>
            <div class="back">
                <p>In the age of information and artificial intelligence, neural networks and deep learning have become fundamental pillars of technological advancement. From machine translation to image recognition, these technologies are transforming the way we interact with the digital world. This page is dedicated to exploring the concepts, applications and advances in neural networks and deep learning, offering a comprehensive overview for both beginners and experts in the field.</p>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="content">
            <div class="front">
                <p>What is Regression?</p>
            </div>
            <div class="back">
                <p>It refers to a type of statistical modeling technique used to predict numerical values ​​based on previously observed data. The main objective of regression is to establish the relationship between one or more independent variables (also called characteristics or predictors) and a dependent variable (also known as the target variable) by fitting a mathematical function. This mathematical function can be linear or non-linear, depending on the nature of the data and the relationship between the variables.</p>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="content">
            <div class="front">
                <p>What is Classification?</p>
            </div>
            <div class="back">
                <p>Les a supervised learning technique used to categorize or label data into different classes or categories. The goal is to assign a label or class to a data instance based on its observed characteristics. In other words, classification seeks to learn a model that can distinguish between different classes from the provided training data.
                During the training process, the classification model is fine-tuned using labeled examples, where each data instance is associated with a known class.</p>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="content">
            <div class="front">
                <p>Applications and Impact.</p>
            </div>
            <div class="back">
                <ul>
                    <p>The applications of neural networks and deep learning are vast and varied. In the health sector, they are used to diagnose diseases and personalize treatments. In the financial industry, they help detect fraud and predict market trends. Additionally, these technologies are revolutionizing the way we interact with smart devices, from virtual assistants to recommendation systems. 
                    The applications and impact of neural networks and deep learning are truly vast and are transforming a variety of industries.</p>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    
    const cards = document.querySelectorAll('.card');

    
    cards.forEach(card => {
        card.addEventListener('click', () => {
            
            card.classList.toggle('flipped');
        });
    });

</script>
{% endblock %}

app/templates/regression.html
{% extends 'base.html' %}

{% block title %}Regression{% endblock %}

{% block content %}
<div class="introContainer2">
    <h2 class="introTitle2">Regression</h2>
</div>
<div class="form-image-container">
    <form id="regression-form" action="{{ url_for('main.regression', user_id=1) }}" method="POST" enctype="multipart/form-data" class="form">
        <div class="form-group">
            <button type="button" class="btn">
                <input type="file" id="dataset" name="dataset" accept=".csv, .xlsx, .xls, .json" class="file-input" />
                <i class="fa-solid fa-file-arrow-up" style="font-size: 15px; margin-right: 5px;"></i>Upload File
            </button>
            <label for="dataset">Upload Dataset (CSV, XLSX, XLS, JSON)</label>
            <span id="fileStatusIcon"><i class="fa-solid fa-circle-xmark" style="color: red; margin-left: 8px;"></i></span>
        </div>
        <div class="form-group">
            <input type="url" id="url" name="url" placeholder=" " />
            <label for="url">Or Enter Dataset URL</label>
        </div>
        <div class="form-group">
            <input type="text" id="input_variables_text" name="input_variables_text" placeholder=" " />
            <label for="input_variables_text">Enter input variables separated by comma</label>
        </div>
        <div class="form-group">
            <input type="text" id="output_variable_text" name="output_variable_text" placeholder=" " />
            <label for="output_variable_text">Enter output variable</label>
        </div>
        <div class="form-group">
            <select id="model" name="model" required>
                <option value="linear">Linear Regression</option>
                <option value="polynomial">Polynomial Regression</option>
                <option value="ridge">Ridge Regression</option>
                <option value="lasso">Lasso Regression</option>
                <option value="neural_network">Neural Network</option>
            </select>
            <label for="model">Select Model Type</label>
        </div>
        <div class="form-group" id="polynomial-degree-group" style="display: none;">
            <input type="number" id="degree" name="degree" min="1" placeholder=" " />
            <label for="degree">Degree (for Polynomial Regression)</label>
        </div>
        <div class="form-group" id="alpha-group" style="display: none;">
            <input type="number" id="alpha" name="alpha" step="0.01" placeholder=" " />
            <label for="alpha">Alpha (for Ridge/Lasso Regression)</label>
        </div>
        <div class="form-group" id="neurons-group" style="display: none;">
            <input type="number" id="neurons" name="neurons" min="1" max="1000" placeholder=" " />
            <label for="neurons">Number of Neurons (for Neural Network)</label>
        </div>
        <div class="form-group" id="hidden-activation-group" style="display: none;">
            <select id="hidden_activation" name="hidden_activation">
                <option value="relu">ReLU</option>
                <option value="sigmoid">Sigmoid</option>
                <option value="tanh">Tanh</option>
                <option value="linear">Linear</option>
            </select>
            <label for="hidden_activation">Select Hidden Activation Function (for Neural Network)</label>
        </div>
        <div class="form-group" id="output-activation-group" style="display: none;">
            <select id="output_activation" name="output_activation">
                <option value="relu">ReLU</option>
                <option value="sigmoid">Sigmoid</option>
                <option value="tanh">Tanh</option>
                <option value="linear">Linear</option>
            </select>
            <label for="output_activation">Select Output Activation Function (for Neural Network)</label>
        </div>
        <div class="form-group" id="layers-group" style="display: none;">
            <input type="number" id="layers" name="layers" min="1" max="10" placeholder=" " />
            <label for="layers">Number of Hidden Layers (for Neural Network)</label>
        </div>
        <div class="form-group" id="epochs-group" style="display: none;">
            <input type="number" id="epochs" name="epochs" min="1" max="1000" placeholder=" " />
            <label for="epochs">Number of Epochs (for Neural Network)</label>
        </div>
        <div id="container">
            <div class="wrapper">
                <button class="button" type="submit">Submit</button>
            </div>
        </div>    
    </form>
    <div class="image">
        <img src="static/AI1.png" alt="Imagen descriptiva o animación">
    </div>
</div>

<script>
    const fileInput = document.getElementById('dataset');
    const fileStatusIcon = document.getElementById('fileStatusIcon');

    fileInput.addEventListener('change', function() {
        if (fileInput.files.length > 0) {
            fileStatusIcon.innerHTML = '<i class="fa-solid fa-circle-check" style="color: #00F10B; margin-left: 8px;"></i>';
        } else {
            fileStatusIcon.innerHTML = '<i class="fa-solid fa-circle-xmark" style="color: red;"></i>';
        }
    });

    document.getElementById('model').addEventListener('change', function () {
        var modelType = this.value;
        document.getElementById('polynomial-degree-group').style.display = (modelType === 'polynomial') ? 'block' : 'none';
        document.getElementById('alpha-group').style.display = (modelType === 'ridge' || modelType === 'lasso') ? 'block' : 'none';
        document.getElementById('neurons-group').style.display = (modelType === 'neural_network') ? 'block' : 'none';
        document.getElementById('hidden-activation-group').style.display = (modelType === 'neural_network') ? 'block' : 'none';
        document.getElementById('output-activation-group').style.display = (modelType === 'neural_network') ? 'block' : 'none';
        document.getElementById('layers-group').style.display = (modelType === 'neural_network') ? 'block' : 'none';
        document.getElementById('epochs-group').style.display = (modelType === 'neural_network') ? 'block' : 'none';
    });

    document.getElementById('regression-form').addEventListener('submit', function(event) {
        event.preventDefault();
        const form = this;
        const formData = new FormData(form);

        const inputVariables = formData.get('input_variables_text');
        const outputVariable = formData.get('output_variable_text');
        const modelType = formData.get('model');

        if (!inputVariables || !outputVariable) {
            alert('Please provide input and output variables.');
            return;
        }

        if (modelType === 'polynomial' && !formData.get('degree')) {
            alert('Please provide a degree for Polynomial Regression.');
            return;
        }

        if ((modelType === 'ridge' || modelType === 'lasso') && !formData.get('alpha')) {
            alert('Please provide an alpha value for Ridge/Lasso Regression.');
            return;
        }

        if (modelType === 'neural_network') {
            if (!formData.get('neurons')) {
                alert('Please provide the number of neurons for Neural Network.');
                return;
            }
            if (!formData.get('hidden_activation')) {
                alert('Please select a hidden activation function for Neural Network.');
                return;
            }
            if (!formData.get('output_activation')) {
                alert('Please select an output activation function for Neural Network.');
                return;
            }
            if (!formData.get('layers')) {
                alert('Please provide the number of hidden layers for Neural Network.');
                return;
            }
            if (!formData.get('epochs')) {
                alert('Please provide the number of epochs for Neural Network.');
                return;
            }
        }

        fetch(form.action, {
            method: 'POST',
            body: formData,
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                window.location.href = data.redirect;
            } else {
                alert('An error occurred while processing your request. Please try again.');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred while processing your request. Please try again.');
        });
    });
</script>

{% endblock %}

app/templates/results.html
{% extends 'base.html' %}

{% block title %}Results{% endblock %}

{% block content %}
<div class="results-container">
    <h2 class="results-title">Training Results</h2>
    {% if plot_path %}
        <div class="plot-container">
            <img src="{{ plot_path }}" alt="Training Plot">
        </div>
    {% else %}
        <p>No results to display.</p>
    {% endif %}
</div>
{% endblock %}